name: Build Windows

on:
    workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile main.py

      - name: Upload built exe as artifact
        uses: actions/upload-artifact@v3
        with:
          name: your-project-build
          path: dist/main.exe
